/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kEgvnGtetni
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Syne } from 'next/font/google'

syne({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card"

export function Component() {
  const [selectedCategory, setSelectedCategory] = useState("maternelle")
  const categoryOptions = [
    { 
      label: "Maternelle", 
      value: "maternelle", 
      items: [
        { name: "TPS", link: "https://example.com/tps" },
        { name: "PS", link: "https://example.com/ps" },
        { name: "MS", link: "https://example.com/ms" },
        { name: "GS", link: "https://example.com/gs" }
      ]
    },
    { 
      label: "Élémentaire", 
      value: "elementaire", 
      items: [
        { name: "CP", link: "https://example.com/cp" },
        { name: "CE1", link: "https://example.com/ce1" },
        { name: "CE2", link: "https://example.com/ce2" },
        { name: "CM1", link: "https://example.com/cm1" },
        { name: "CM2", link: "https://example.com/cm2" }
      ]
    },
    { 
      label: "Collège", 
      value: "college", 
      items: [
        { name: "6e", link: "https://example.com/6e" },
        { name: "5e", link: "https://example.com/5e" },
        { name: "4e", link: "https://example.com/4e" },
        { name: "3e", link: "https://example.com/3e" }
      ]
    },
    { 
      label: "Lycée", 
      value: "lycee", 
      items: [
        { name: "Seconde", link: "https://example.com/seconde" },
        { name: "Première", link: "https://example.com/premiere" },
        { name: "Terminale", link: "https://example.com/terminale" }
      ]
    }
  ];
  
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" className="flex items-center gap-2 font-bold text-xl" prefetch={false}>
            <BookIcon className="h-6 w-6" />
            FEIM Services
          </Link>
          {/* <nav className="hidden md:flex items-center gap-4">
            <Link href="#" className="hover:text-accent" prefetch={false}>
              Fournitures
            </Link>
            <Link href="#" className="hover:text-accent" prefetch={false}>
              À propos
            </Link>
            <Link href="#" className="hover:text-accent" prefetch={false}>
              Contact
            </Link>
          </nav>
          <Button variant="outline" className="md:hidden">
            <MenuIcon className="h-5 w-5" />
          </Button> */}
        </div>
      </header>
      <main className="flex-1 bg-background text-foreground">
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container mx-auto px-6">
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <h1 className="text-4xl font-bold mb-6">Découvrez nos fournitures scolaires</h1>
                <p className="text-lg text-muted-foreground mb-8">
                  Trouvez tout ce dont vous avez besoin pour une année scolaire réussie.
                </p>
                <div className="flex gap-4">
                  <Button onClick={() => window.location.hash = 'fournitures'}>Voir les fournitures</Button>
                  <Button variant="outline"onClick={ () => window.location.href = "https://wa.me/2250505606677?text=Bonjour,%20je%20souhaite%20obtenir%20des%20informations%20sur%20les%20fournitures."}> Contactez-nous</Button>

                </div>
              </div>
              <div>
                <img
                  src="/fournitures.png"
                  width="550"
                  height="400"
                  alt="Fournitures scolaires"
                  className="rounded-lg object-cover"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container mx-auto px-6">
            <div className="text-center mb-12">
              <h2 id="fournitures" className="text-3xl font-bold mb-4">Nos catégories de fournitures</h2>
              <p className="text-muted-foreground">Découvrez nos différentes catégories de fournitures scolaires.</p>
            </div>
            <div className="relative">
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="outline" className="w-full md:w-auto flex items-center justify-between gap-2">
                    {categoryOptions.find((option) => option.value === selectedCategory)?.label}
                    <ChevronDownIcon className="h-4 w-4" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="start" className="w-full md:w-auto">
                  {categoryOptions.map((option) => (
                    <DropdownMenuItem
                      key={option.value}
                      onClick={() => setSelectedCategory(option.value)}
                      className={selectedCategory === option.value ? "bg-accent text-accent-foreground" : ""}
                    >
                      {option.label}
                    </DropdownMenuItem>
                  ))}
                </DropdownMenuContent>
              </DropdownMenu>
              <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8 mt-8">
                {categoryOptions
                  .find((option) => option.value === selectedCategory)
                  ?.items.map((item) => (
                    <Card key={item.name}>
                      <CardHeader>
                        <CardTitle>{item.name}</CardTitle>
                      </CardHeader>
                      <CardContent>
                        <p>
                          Tout le necessaire pour la classe de {item.name}
                        </p><br></br>
                      <div className="flex justify-center">
                        <Link 
                          className="bg-primary text-white py-2 px-4 rounded hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-600 focus:ring-opacity-50" 
                          target="_blank" 
                          href="#fournitures">
                          Voir la liste de fournitures
                        </Link>
                      </div>
                      </CardContent>
                    </Card>
                  ))}
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container mx-auto px-6">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-bold mb-4">Pourquoi choisir FEIM Services ?</h2>
              <p className="text-muted-foreground">
                Découvrez les avantages de notre service de fournitures scolaires.
              </p>
            </div>
            <div className="grid md:grid-cols-2 gap-5">
              <div className="bg-muted p-6 rounded-lg">
                <TruckIcon className="h-8 w-8 mb-4 text-primary" />
                <h3 className="text-xl font-bold mb-2">Livraison rapide</h3>
                <p className="text-muted-foreground">Recevez vos commandes rapidement et en toute sécurité.</p>
              </div>
              <div className="bg-muted p-6 rounded-lg">
                <ShoppingCartIcon className="h-8 w-8 mb-4 text-primary" />
                <h3 className="text-xl font-bold mb-2">Prix compétitifs</h3>
                <p className="text-muted-foreground">Bénéficiez de nos tarifs avantageux sur tous nos produits.</p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted text-muted-foreground py-6 px-4">
        <div className="container mx-auto flex items-center justify-between">
          <p>&copy; 2024 FEIM Services. Tous droits réservés.</p>
          <nav className="flex items-center gap-4">
            <Link href="#" className="" prefetch={false}>
              Mentions légales
            </Link>
            <Link href="#" className="" prefetch={false}>
              Politique de confidentialité
            </Link>
          </nav>
        </div>
      </footer>
      <div className="fixed bottom-6 right-6">
        <Button size="icon" className="rounded-full shadow-lg" onClick={ () => window.location.href = "https://wa.me/2250505606677?text=Bonjour,%20je%20souhaite%20obtenir%20des%20informations%20sur%20les%20fournitures."}>
          <PhoneIcon className="h-6 w-6" />
          <span className="sr-only">Nous contacter</span>
        </Button>
      </div>
    </div>
  )
}

function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}


function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}

function PhoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}



function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}


function TruckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2" />
      <path d="M15 18H9" />
      <path d="M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14" />
      <circle cx="17" cy="18" r="2" />
      <circle cx="7" cy="18" r="2" />
    </svg>
  )
}
